# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "release/TagCreate_1-0-0" ]
  pull_request:
    branches: [ "release/TagCreate_1-0-0" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  APINAME : "TagCreate"
  JIRA_VERSION : "TagCreate_1-0-0"
  latest_tagname : ""
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "${APINAME}" 
          echo "${JIRA_VERSION}"
          
      - name: Run a script
        run: /createTag.sh
